# Generated by Django 4.1.6 on 2023-02-06 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("job_title", models.CharField(max_length=255)),
                ("job_company", models.CharField(max_length=255)),
                ("job_location", models.CharField(max_length=255)),
                ("post_time", models.CharField(max_length=100)),
                ("access_link", models.URLField()),
                ("is_job_still_available", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
