# Generated by Django 4.1.6 on 2023-02-06 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="job",
            unique_together={("job_title", "job_company", "job_location")},
        ),
    ]
