# Generated by Django 4.1.6 on 2023-02-06 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_job_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="access_link",
            new_name="job_link",
        ),
    ]
