# Generated by Django 4.1.6 on 2023-02-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_rename_access_link_job_job_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_link",
            field=models.URLField(max_length=350),
        ),
    ]
