# Generated by Django 4.1.6 on 2023-02-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_alter_job_job_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company_logo_url",
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
    ]
