# Generated by Django 4.1.6 on 2023-02-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_job_company_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="salary_range",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
