# Generated by Django 4.1.6 on 2023-02-07 03:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_job_salary_range"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="salary_range",
        ),
    ]
