# Generated by Django 4.1.6 on 2023-02-06 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_myuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
