# Generated by Django 4.1.6 on 2023-02-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_myuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
    ]
